### ISSUE TITLE
Remove PersistentVolumeClaims from being created by Terraform

### ISSUE THREAD

**Issue by derekbelrose** [jhu-library-operations/tf-mod-aws-efs-pv-k8s#11]
Let's lay it out here.  Developers and Operations should agree, beforehand, on what a PV should be called and developers should be creating their own PVCs.

If this is agreed with, we should remove PVCs from being created by Terraform and, instead, create them in the main application.

**Comment by jhujasonw** [comment]
This sounds like an excellent idea.

**Comment by derekbelrose** [comment]
And so it is written!

Consensus is made 🥇
